on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  OurSpecialJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl 'wttr.in/Nairobi?format=%T,%l,%c,%t\n&m' >> output.txt
      - run: |
          git config --global user.name "Automatic Action"
          git config --global user.email "automatic@users.noreply.github.com"
          git commit -am "Automated Commit"
          git push origin main
        
      
