on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  OurSpecialJob:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - uses: actions/checkout@v3
      - run: find .
      
